plugins {
    id 'fabric-loom' version '1.1-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // Add repositories necessary for Fabric dependencies
    maven { url = "https://fabricmc.net" }
    mavenCentral()
}
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    // CHANGE THIS LINE: This forces Loom to use identity mappings safely
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}


processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    // Minecraft 1.19.4 requires Java 17 toolchains
    it.options.release = 17
    it.options.encoding = "UTF-8"
}

java {
    // Automatically bundle a sources JAR alongside your mod compilation
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}
